name: CI
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo hello 

      - name: Run a multi-line script
        run:
          echo Add other actions to build, 
          echo test, and deploy your project.

deploy-test:
  runs-on: ubuntu-latest
  environment: test
  needs: [build]
  steps:
    - uses: actions/checkout@v4

    - name: eploy to test
      run: echo 'deploy test'

deploy-prod:
  runs-on: ubuntu-latest
  envrionment: prod
  needs: [deploy-test]
  steps:
    - uses: action/achekout@v4

    - name: deploy to prod
      run: echo 'deploy prod'
    
